CREATE TYPE shipment_state AS ENUM (
  'BOOKED', 'PICKUP_ASSIGNED', 'PICKED_UP', 'HANDED_TO_PICKUP_VAN',
  'AWAITING_SELF_DROP',
  'AT_ORIGIN_HUB', 'ORIGIN_HUB_PROCESSING', 'IN_TAKEOFF_BAG',
  'DISPATCHED_TO_AIRPORT', 'AT_AIRPORT', 'DEPARTED', 'LANDED',
  'DISPATCHED_TO_HUB', 'AT_DEST_HUB', 'DEST_HUB_PROCESSING',
  'HANDED_TO_DROP_VAN', 'DROP_ASSIGNED', 'DROP_COLLECTED', 'DROPPED',
  'AWAITING_HUB_COLLECT', 'HUB_COLLECTED',
  'PICKUP_FAILED', 'DELIVERY_FAILED',
  'RTO_INITIATED', 'RTO_IN_TRANSIT', 'RTO_COMPLETED',
  'CANCELLED'
);

CREATE TYPE customer_type AS ENUM ('B2C', 'B2B', 'C2C');
CREATE TYPE delivery_type AS ENUM ('INTERCITY', 'SAME_CITY');
CREATE TYPE payment_mode  AS ENUM ('PREPAID', 'COD');
CREATE TYPE pickup_type   AS ENUM ('DA_PICKUP', 'SELF_DROP');
CREATE TYPE drop_type     AS ENUM ('DA_DELIVERY', 'HUB_COLLECT');
