package com.oneday.pricing.service.impl;

import com.oneday.common.domain.enums.CustomerType;
import com.oneday.common.domain.enums.DeliveryType;
import com.oneday.common.port.dto.QuoteRequest;
import com.oneday.pricing.config.PricingProperties;
import com.oneday.pricing.domain.CityPairRate;
import com.oneday.pricing.domain.RateCard;
import com.oneday.pricing.repository.CityPairRateRepository;
import com.oneday.pricing.repository.RateCardRepository;
import com.oneday.pricing.service.NoRateConfiguredException;
import org.junit.jupiter.api.Test;

import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class RateCardServiceImplTest {

    private final RateCardRepository rateCards = mock(RateCardRepository.class);
    private final CityPairRateRepository pairRates = mock(CityPairRateRepository.class);
    private final RateCardServiceImpl service =
            new RateCardServiceImpl(rateCards, pairRates, new PricingProperties());

    private RateCard card() {
        RateCard c = new RateCard();
        c.setSameCityBasePricePaise(5000);
        return c;
    }

    @Test
    void resolvesActivePublishedCardForB2c() {
        RateCard active = card();
        when(rateCards.findFirstByCustomerTypeAndStatus(CustomerType.B2C, "ACTIVE"))
                .thenReturn(Optional.of(active));

        QuoteRequest req = new QuoteRequest(CustomerType.B2C, DeliveryType.INTERCITY,
                "BLR", "DEL", 1000, null, null, null);
        assertThat(service.resolveForQuote(req)).isSameAs(active);
    }

    @Test
    void resolvesByB2bRateCardIdWhenPresent() {
        UUID cardId = UUID.randomUUID();
        RateCard b2b = card();
        when(rateCards.findById(cardId)).thenReturn(Optional.of(b2b));

        QuoteRequest req = new QuoteRequest(CustomerType.B2B, DeliveryType.INTERCITY,
                "BLR", "DEL", 1000, null, cardId, null);
        assertThat(service.resolveForQuote(req)).isSameAs(b2b);
    }

    @Test
    void missingPublishedCardThrows() {
        when(rateCards.findFirstByCustomerTypeAndStatus(any(), any())).thenReturn(Optional.empty());
        QuoteRequest req = new QuoteRequest(CustomerType.B2C, DeliveryType.INTERCITY,
                "BLR", "DEL", 1000, null, null, null);
        assertThatThrownBy(() -> service.resolveForQuote(req))
                .isInstanceOf(NoRateConfiguredException.class);
    }

    @Test
    void basePriceLooksUpNormalisedCityPair() {
        RateCard c = card();
        // id is generated by JPA; stub the repo to answer for whatever id the card has (null here).
        CityPairRate rate = new CityPairRate();
        rate.setBasePricePaise(15700);
        when(pairRates.findByRateCardIdAndOriginCityAndDestCity(c.getId(), "BLR", "DEL"))
                .thenReturn(Optional.of(rate));

        long price = service.basePriceFor(c, "Bengaluru", "Delhi", DeliveryType.INTERCITY);
        assertThat(price).isEqualTo(15700);
    }

    @Test
    void sameCityUsesCardSameCityBase() {
        RateCard c = card();
        assertThat(service.basePriceFor(c, "BLR", "BLR", DeliveryType.SAME_CITY)).isEqualTo(5000);
    }

    @Test
    void missingPairRateThrows() {
        RateCard c = card();
        when(pairRates.findByRateCardIdAndOriginCityAndDestCity(any(), any(), any()))
                .thenReturn(Optional.empty());
        assertThatThrownBy(() -> service.basePriceFor(c, "MAA", "DEL", DeliveryType.INTERCITY))
                .isInstanceOf(NoRateConfiguredException.class);
    }
}
